### ISSUE TITLE
np.nan / np.NaN issue on numpy => 2.0.0

### ISSUE THREAD

**Issue by ayumutominaga** [matthewgilbert/pdblp#107]
#### Problem description

pdblp got error message when data field is empty or NOT_APPLICABLE_TO_REF_DATA.
It looks numpy==2.0.0 changed some exception handling. 
Could you amend np.nan / np.NaN for numpy => 2.0.0 ?

Thanks a lot ... very useful blp and pdblp

#### Version Information
pdblp==0.1.8

**Comment by matthewgilbert** [comment]
Happy to take a PR on this
