### ISSUE TITLE
What is the latest version of python this will work with?

### ISSUE THREAD

**Issue by NoahKauffman** [matthewgilbert/pdblp#16]
Running into some issues using this with some other code that references packages that are only compatible with python 3.6.  

What is the latest version of python that this will work with?  And is there any hack if I am working in 3.6 whereby I could get data to run (other than running commands such as os.system('python2.7 etc..')?

**Comment by matthewgilbert** [comment]
I believe this should work with any python 3.x, what's the specific issue with the package you are having using python 3.6?

**Comment by NoahKauffman** [comment]
I get the following error:

C:\Windows\system32>conda install -n py36 -c dsm blpapi
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - blpapi -> python 2.7*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

But a bit confused because bloomberg says that they don't have a 3.6 release.  The last release they have 
3.5:
https://bintray.com/bloomberg/BLPAPI-Experimental-Generic/download_file?file_path=blpapi-3.9.0b1.win32-py3.5.msi

64-bit:
https://bintray.com/bloomberg/BLPAPI-Experimental-Generic/download_file?file_path=blpapi-3.9.0b1.win-amd64-py3.5.msi

And that release is not posted here: https://www.bloomberg.com/professional/support/api-library/

However Bloomberg did say that some people had managed to get it working in 3.6 but that they don't support it.  

Do you have any thoughts on this error above?

**Comment by matthewgilbert** [comment]
This is more to do with installing `blpapi` than with `pdblp` which sits on top of `blpapi`.  The issue you are having trying to `conda` install from the `dsm` channel is that for windows there is only a package for python 2.7. This has nothing to do with `blpapi` compatibility, simply the person who runs this channel on Anaconda Cloud has not packaged `blpapi` for more recent python versions of windows.

I don't use windows very often so have no experience getting `blpapi` to run with python 3.6. When I have used windows I just used the most recent binary installer from https://www.bloomberg.com/professional/support/api-library/

**Comment by NoahKauffman** [comment]
Great, thanks.  OK, I got it working for 3.5.  Not sure what people are doing to get it working for 3.6.

The folder location for the 3.5 blpapi got installed at C:\Python35\Lib\site-packages\blpapi ... I suppose its not as simple as dragging that folder into C:\Python36\Lib\site-packages\blpapi.  Thanks anyways for the response!

**Comment by MarekOzana** [comment]
I use pdblp with python 3.6.3,
You could either 

- install blpapi from [Bloomberg's Python Experimental Release](https://software.tech.bloomberg/BLPAPI-Experimental-Generic/blpapi_python_3.9.0.zip)
or 
- you could install it from conda macinv channel: `conda install -c macinv blpapi`
I hope it helps.
