### ISSUE TITLE
pulling field for multiple tickers returns results for only 4 tickers

### ISSUE THREAD

**Issue by NoahKauffman** [matthewgilbert/pdblp#18]
con = pdblp.BCon(debug=False, port=8194)
con.start()

ticker_list = [lots of tickers]
sd = datetime.datetime(2016, 1, 1, 0,0,0,0).strftime('%Y%m%d')
ed = str(datetime.datetime.today().strftime('%Y%m%d'))
cols = ['PX_VOLUME']
df = con.bdh( tickers, cols,sd,ed) 

Originally i tried pulling for say 100 or more tickers...  However, when I paired it down to just 5 tickers, the result set still only returns results for the first 4 tickers in the list.  

Am I supposed to override anything, like timeout or call some other function if i am requesting field(s) for an entire portfolio?

**Comment by matthewgilbert** [comment]
Could you show some reproducible sample output, it's impossible for me to diagnose currently. Specifically can you set debug to `True` and include that output in your question. Could you also show the list of your 5 tickers that are causing the problem and `df.head()`

**Comment by NoahKauffman** [comment]
sorry, nevermind.  must have been something I was doing.  Cannot recreate the issue any more.
