### ISSUE TITLE
bloomberg logout issue

### ISSUE THREAD

**Issue by richardtbenade** [matthewgilbert/pdblp#27]
Hi there. I've been having issues using pdblp after being automatically logged out from bloomberg (main terminal). I often need to manually log back in in order to get pdblp to work. Is it possible to initiate a logon from pdblp?

**Comment by matthewgilbert** [comment]
Yes my understanding is that the services that `pdblp` connect to, e.g. `//blp/refdata`, also close when the terminal is logged out so you would need an active terminal connection.
