### ISSUE TITLE
Unknown security from a list of valid securities

### ISSUE THREAD

**Issue by gflores87** [matthewgilbert/pdblp#31]
I'm querying ten tickers using
`con.ref(_tickers, "PX_MID")`
However, one of them refers to an option whose strike is so large that there is no trading and thus, there is no such ticker in bloomberg. 
The way pdblp works is that if I query 9 valid tickers and one invalid ticker then my entire execution stops. How can I handle the code such that execution continues? Is is possible to just ignore the invalid ticker?

**Comment by matthewgilbert** [comment]
Currently passing non valid tickers results in errors. This is discussed in #13 and a result of changes in 659c0d2a8af7f8d24cf53adeb5f3790774160cdc.

A work around for this would be to drop erroneous tickers, which you could parse from the error message. This is a hacky work around that wouldn't be very efficient on your data caps, but something like this would work.


```python
import pdblp

con = pdblp.BCon()
con.start()
tickers = ["EJ8189684 Corp", "not_a_ticker", "also_not_a_ticker"]

while True:
    try:
        df = con.ref(tickers, ["MATURITY", "NXT_CALL_DT"])
        break
    except ValueError as e:
        problem_ticker = e.args[0].split()[-1]
        print("Removing {0} from {1}".format(problem_ticker, tickers))
        tickers = list(set(tickers).difference([problem_ticker]))
```

What is the use case that leads to you not knowing the tickers in advance?

**Comment by gflores87** [comment]
Thank you for the workaround! Agree, there seems to not be a pretty solution to this issue. 
The cause is that I'm querying option tickers. The strike is a function of certain market values which in some special circumstances may produce a strike that is so out of the money that there is no market data and hence the error. The only way to know in advance would be to query the full option chain and extract the largest and smallest strikes and compare my list of strikes to such values. Seems like that is the way to go given the alternatives.

Again, thank you for your help

**Comment by pepicello** [comment]
> What is the use case that leads to you not knowing the tickers in advance?

IMHO it would be great to have such an option on tickers. There are a few use case I can think of where tickers are not known in advance:
    - Ticker changes: Bloomberg does not deal gracefully with all ticker changes, especially if dealing with old point in time data. Sometimes tickers are completely deleted, so a list of tickers could become invalid from one day to the other.
     - Using other references other than tickers: bdh and ref also works with FIGIs (ID_BB_GLOBAL). If you need to work out the validity of FIGIs and reverse engineer the ticker, for example, this is a case where having the exception raised at each invalid FIGI is counterproductive.

**Comment by wochner** [comment]
Could this be implemented with an optional parameter similar to how it was implemented [here](https://github.com/bpsmith/tia/blob/master/tia/bbg/bbg_com.py) ?

**Comment by wochner** [comment]
Something along the lines of the below would be nice in the bloomberg query functions and a parameter that would enable it and automatically "ignore" security errors. 


```
import pdblp
import pandas as pd

con = pdblp.BCon()
con.start()
tickers = ["EJ8189684 Corp", "not_a_ticker", "also_not_a_ticker"]

df_out = pd.DataFrame()
L = []


for i in tickers:
    try:
        df = con.ref(i, ["MATURITY", "NXT_CALL_DT"])
        df_out = df_out.append(df)
    except ValueError as e:
        problem_ticker = e.args[0].split()[-1]
        L.append(problem_ticker)


problem_tickers = pd.DataFrame(L, columns=['TICKER']) 
       
```
I agree with @pepicello there are many use cases were Tickers are changed or get obsolete, especially in the fixed income world.

**Comment by matthewgilbert** [comment]
I generally don't like the idea of just returning NaN's for arbitrary tickers, with some exceptions as discussed in https://github.com/matthewgilbert/pdblp/issues/13. This becomes quite challenging to do in a consistent way across `ref` / `bdh`. If you want to query for valid tickers I think using the `//blp/instruments` service and writing a `instrumentListRequest` would be cleaner.

**Comment by 06agyepo** [comment]
I tried the error handler code above by both @matthewgilbert  and @wochner and neither were successful as it just keeps running without seeming to come to an end.   I have the same problem of valid cusips in Bloomberg not returning any reference data while using the con.ref code. For example: con.ref('45779BCC15 Corp', 'YAS_BNCHMRK_BOND_YLD' ) code from pdblp package returns the "Unknown security" error. The error seems to be occurring with CMBS bonds (commercial mortgage backed securities) and it would be very much appreciated to have an error handler code that would skip over these problematic securities while looping through a list or to have it built-in to the pdblp package which I love by the way.

Can anyone please help with issue? Here's my sample code and the problematic cusip is the 3rd one in the list but this code does not work:

import pdblp
import pandas as pd

con = pdblp.BCon()
con.start()

tickers = ['00206RGB2 Corp', '004331AA2 Corp', '45779BCC15 Corp', '00889YAA9 Corp']
length = len(tickers)
Benchmark_SecYld = pd.DataFrame()
L = []

while True:
    try:
        for i in range(length): 
            dfTemp = con.ref(tickers[i], 'YAS_BNCHMRK_BOND_YLD')
            Benchmark_SecYld = Benchmark_SecYld.append(dfTemp, sort=False, ignore_index=True)
        break
    except ValueError as e:
        problem_ticker = e.args[0].split()[-1]
        L.append(problem_ticker)
        tickers = list(set(tickers).difference([problem_ticker]))    

problem_tickers = pd.DataFrame(L, columns=['TICKER'])

**Comment by 06agyepo** [comment]
Here's the text file for the code with proper formatting by the way. Thanks for the help!!!

[pdblp problem script.txt](https://github.com/matthewgilbert/pdblp/files/5393715/pdblp.problem.script.txt)

**Comment by 06agyepo** [comment]
Problematic valid BBG cusips are an issue in the fixed income space while using the pdblp package
