### ISSUE TITLE
override to ref history 

### ISSUE THREAD

**Issue by superbobstar** [matthewgilbert/pdblp#36]
Hi 
When I try to override ref_hist it errors out when you try to combine overrides with bulk reference data.  I think that the overrides are not being combined with the dates.
```python
con.ref_hist(['BAC US EQUITY'] ,['DDIS_AMT_OUTSTANDING'], dates=df1['Quarter'],
             [('DDIS_CURRENCY','USD')] ,date_field="DDIS_HISTORY_OVERRIDE")
```

**Comment by matthewgilbert** [comment]
Please post a reproducible minimal example causing the error with `con.debug = True` set.

**Comment by superbobstar** [comment]
Hi,  Here is a good example.  It runs fine when using the dates only however when I include the override statement it errors.  Below the line i tested running it without the date_field override and it is interesting how it combines them. 

con.ref_hist(['BAC US EQUITY']
,['DDIS_AMT_OUTSTANDING']
,dates = ['2016Q1','2016Q2']
,[('DDIS_CURRENCY','USD')]
,date_field="DDIS_HISTORY_OVERRIDE"
)

  File "<ipython-input-82-e14b4b16b2ac>", line 4
    ,[('DDIS_CURRENCY','USD')]
SyntaxError: non-keyword arg after keyword arg

-------------------------------------------------------------------------------------------
con.ref_hist(['BAC US EQUITY']
,['DDIS_AMT_OUTSTANDING']
#,dates = ['2016Q1','2016Q2']
,[('DDIS_CURRENCY','USD')]
#,date_field="DDIS_HISTORY_OVERRIDE"
)

DEBUG:root:Sending Request:
 ReferenceDataRequest = {
    securities[] = {
        "BAC US EQUITY"
    }
    fields[] = {
        "DDIS_AMT_OUTSTANDING"
    }
    overrides[] = {
        overrides = {
            fieldId = "REFERENCE_DATE"
            value = "('DDIS_CURRENCY', 'USD')"
        }
    }
}

DEBUG:root:Message Received:
 ReferenceDataResponse = {
    securityData[] = {
        securityData = {
            security = "BAC US EQUITY"
            eidData[] = {
            }
            fieldExceptions[] = {
            }
            sequenceNumber = 0
            fieldData = {
                DDIS_AMT_OUTSTANDING = 202631594.904144
            }
        }
    }
}

Out[85]: 
                   date                 field         ticker         value
0  (DDIS_CURRENCY, USD)  DDIS_AMT_OUTSTANDING  BAC US EQUITY  2.026316e+08

**Comment by matthewgilbert** [comment]
`SyntaxError: non-keyword arg after keyword arg` is indicating the problem. This has nothing to do with `pdblp` but is related to the fact that this is not valid python syntax. You need to place keyword arguments **after** non keyword arguments.

```python
con.ref_hist(['BAC US EQUITY'], ['DDIS_AMT_OUTSTANDING'] ,dates=['2016Q1','2016Q2'],
             ovrds=[('DDIS_CURRENCY','USD')], date_field="DDIS_HISTORY_OVERRIDE")
```

As an aside, when filing issues please look into formatting your messages appropriately.

**Comment by superbobstar** [comment]
Thank you!
