### ISSUE TITLE
Clumsy start and stop

### ISSUE THREAD

**Issue by tschm** [matthewgilbert/pdblp#7]
Matthew, you can use the contextmanager to make the construction of your connectivity a lot more slick, e.g. with

```
import pdblp
from contextlib import contextmanager


@contextmanager
def b_berg(debug=False):
    con = pdblp.BCon(debug=debug)
    con.start()
    try:
        yield con
    finally:
        con.stop()
```

you can now use

```
        with b_berg(debug=False) as bb:
            return bb.ref(tickers, fields, ovrds=ovrds)

```

Please update

**Comment by matthewgilbert** [comment]
Okay this should be working now. I don't currently have a connection to Bloomberg though so it is problematic for me to test things.
