### ISSUE TITLE
BSRCH help

### ISSUE THREAD

**Issue by sswat38** [matthewgilbert/pdblp#97]
#### Code Sample, a copy-pastable example if possible

```python
# Your code here, this should be a minimal reproducible example, see https://stackoverflow.com/help/mcve
import pdblp

con = pdblp.BCon(debug=True, port=8194, timeout=5000)
con.start()

#this works
con.bdh('SPY US Equity', 'PX_LAST',
                '20150629', '20150630')

#this doesn't work
con.bsrch("COMDTY:NGFLOW")
```
#### Problem description

Hi - thank you for building this package, it's great! I am new to python and Bloomberg and was exploring the functionalities, and wanted to check if anyone knew why I was experiencing this behavior with the BSRCH function. I am able to run bdh functions, but BSRCH gives an error. Am I required to do any extra setup on Bloomberg/python?

![pdblp_error](https://user-images.githubusercontent.com/58872662/128961575-2e4b3180-a305-4bca-8738-86d0c2800666.JPG)

Secondly, what are the possible things I can use BSRCH to pull out? Is there any documentation I can read to figure that out?

#### Version Information
'0.1.8'

**Comment by EricNeville** [comment]
Did you resolve this?
